# Generated by Django 4.2.5 on 2024-02-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0036_store_channel_store_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='estimated_completion_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='floors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='no_of_rooms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_area',
            field=models.TextField(null=True),
        ),
    ]
