# Generated by Django 4.2.5 on 2024-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0037_store_estimated_completion_date_store_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='BACKLOG', max_length=50),
        ),
    ]
