# Generated by Django 4.2.5 on 2024-07-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0040_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionimages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
